- hosts: all

  gather_facts: no

  vars:
    ansible_user: user
    ansible_host_key_checking: no

  tasks:
    - name: Wait for target to be up
      wait_for_connection:

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present
